export const acronymsAndGlossaryTranslations = {
  termB100: "B100",
  defB100: "B100 Biodiesel RME.",
  termGCO2e: "gCO2e",
  defGCO2e: "Grams of CO2 equivalent. Unit of measurement for GHG emissions.",
  termGHG: "GHG",
  defGHG:
    "Greenhouse gases, so named because their ability to contain heat if accumulated in a large enough scale is similar to that of a greenhouse, are generated in plentiful ways all around us – most through land use (agriculture) and combustions in production facilities. The most common ones are carbon dioxide (CO2), nitrous oxide (N2O) and methane (CH4), although there are more hazardous ones in the form of hydrofluorocarbons (HFCs), perfluorocarbons (PFCs), sulphur hexafluoride (SF6) and nitrogen trifluoride (NF3). As far as reporting standards go, these are often collectively expressed as CO2-equivalents, but, if possible, the GHG Protocol states that these gases should be reported individually as well.",
  termHVO100: "HVO100",
  defHVO100: "HVO100 Renewable Diesel.",
  termISCC: "ISCC",
  defISCC:
    "International Sustainability & Carbon Certification, a globally leading and acknowledged, independent sustainability certification system, supporting sustainable, fully traceable, deforestation-free and climate-friendly supply chains.",
  termLHV: "LHV",
  defLHV:
    "Lower Heating Value. A measure of the energy provided from combustion of a fuel.",
  termRenewableDiesel: "Renewable diesel",
  defRenewableDiesel: "Paraffinic diesel made from renewable sources.",
  termRTFO: "RTFO",
  defRTFO: "Renewable Transport Fuels Obligation.",
  termTTW: "TTW",
  defTTW:
    "Tank-to-Wheel. TTW emissions are generated when driving the vehicle.",
  termWTT: "WTT",
  defWTT:
    "Well-to-Tank. WTT emissions are generated from fuel production, from the primary energy source to the point of dispensing.",
  termWTW: "WTW",
  defWTW:
    "Well-to-Wheel. WTW emissions are all the emissions generated by a vehicle in-use. This is the sum of the WTT and TTW emissions.",
  termAF: "AF",
  defAF:
    "Animal Fats. Renewable raw material for biofuels production. Animal Fats Category 1 is included in REDII Annex 9B.",
  termCO2eq: "CO2eq",
  defCO2eq:
    "CO2 equivalent, or carbon dioxide equivalent, is a standard unit used to measure and express the total impact of different greenhouse gases in terms of the amount of carbon dioxide that would exert the same global warming potential over a specified timeframe. It helps quantify and compare the overall contribution of various greenhouse gases to climate change.",
  termCSRD: "CSRD",
  defCSRD:
    "Corporate Sustainability Reporting Directive. CSRD is a regulatory framework aimed at enhancing and standardizing corporate sustainability reporting within the European Union (EU). It mandates companies to disclose information on environmental, social, and governance (ESG) matters to foster transparency and comparability, facilitating sustainable investment decisions.",
  termESG: "ESG",
  defESG: "Environmental, Social and Governance.",
  termGhgBaseline: "GHG Baseline",
  defGghBaseline:
    "Similarly to the fossil fuel comparator, the GHG baseline is a metric, used to calculate GHG emissions, emissions saved, or percentage values of environmental impact compared to the standardized fossil-based values.",
  termGhgProtocol: "GHG Protocol",
  defGhgProtocol:
    "Greenhouse Gas Protocol, an international accounting tool for measuring and managing greenhouse gas emissions. It sets standards for companies and organizations to quantify and report their emissions, providing a framework for businesses to assess and address their environmental impact.",
  termMJ: "MJ",
  defMJ: "Megajoule, unit of energy content.",
  termPFAD: "PFAD",
  defPFAD:
    "Palm Fatty Acid Distillate. Renewable raw material for biofuels production",
  termPLC: "PLC",
  defPLC: "Product life cycle.",
  termPOME: "POME",
  defPOME:
    "Palm Oil Mills. Renewable raw material for biofuels production, included in REDII Annex 9A.",
  termPoS: "PoS",
  defPoS:
    "Proof of Sustainability declaration documents calculated emission and reduction values for delivered renewable fuel and biofuel. The PoS may be issued under voluntary certification schemes, such as ISCC.",
  termRED: "RED",
  defRED:
    "Renewable Energy Directive. The Renewable Energy Directive is the legal framework for the development of clean energy across all sectors of the EU economy, supporting cooperation between EU countries towards this goal.",
  termRSO: "RSO",
  defRSO:
    "Rapeseed oil / canola. Renewable raw material for biofuels production",
  termSBTi: "SBTi",
  defSBTi: "Science Based Targets initiative",
  termTCO2e: "tCO2e",
  defTCO2e: "Tons of CO2 equivalent. Unit of measurement for GHG emissions.",
  termUCO: "UCO",
  defUCO:
    "Used Cooking Oil. Renewable raw material for biofuels production, included in REDII Annex 9B.",
};
