import type { ThemeOptions } from "@mui/material";

export const typography: ThemeOptions["typography"] = (palette) => ({
  fontFamily: "Montserrat, Open Sans, Dinot",
  h1: {
    fontSize: "34px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "42px",
    color: palette.primary.main,
  },
  h2: {
    fontSize: "30px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "30px",
  },
  h3: {
    fontSize: "24px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "29px",
  },
  h4: {
    fontSize: "18px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "22px",
  },
  h5: {
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "19px",
  },
  h6: {
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "17px",
  },
  subheading1: {
    fontWeight: 500,
    fontSize: "14px",
    lineHeight: "17px",
    color: palette.primary.light,
  },
  body1: {
    fontWeight: 400,
    fontSize: "14px",
    lineHeight: "15px",
    color: palette.common.black,
  },
  body2: {
    fontWeight: 400,
    fontFamily: "Open Sans",
    fontSize: "12px",
    lineHeight: "15px",
    color: palette.common.black,
  },
  body3: {
    fontWeight: 400,
    fontSize: "12px",
    lineHeight: "15px",
    color: palette.common.black,
  },
  body4: {
    fontWeight: 400,
    fontSize: "12px",
    lineHeight: "15px",
    color: palette.common.black,
  },

  button: {
    fontWeight: 500,
    fontSize: "14px",
    lineHeight: "24px",
    color: palette.common.black,
  },
  button1: {
    fontWeight: 600,
    fontSize: "14px",
    lineHeight: "24px",
    color: palette.common.black,
  },
  datatable: {
    fontWeight: 700,
    fontSize: "14px",
    color: palette.common.black,
  },
  tooltip: {
    fontWeight: 500,
    fontSize: "10px",
    lineHeight: "15px",
    color: palette.Gray1.main,
  },
  subtitle1: {
    fontWeight: 400,
    fontSize: "12px",
    lineHeight: "15px",
    color: palette.common.black,
  },
  subtitle2: {
    fontWeight: 500,
    fontSize: "12px",
    lineHeight: "15px",
    color: palette.Gray1.main,
  },
  label: {
    fontWeight: 500,
    fontSize: "10px",
    lineHeight: "12px",
    fontFamily: "Dinot",
    color: palette.Gray1.main,
  },
  error: {
    fontWeight: 600,
    fontSize: "14px",
    lineHeight: "12px",
    fontFamily: "Dinot",
    color: palette.error.main,
  },
  pdfHeaderTitle: {
    fontWeight: 500,
    fontSize: "24px",
    lineHeight: "28px",
    color: palette.primary.main,
  },
  pdfPageTitle: {
    fontWeight: 700,
    fontSize: "24px",
    lineHeight: "28px",
    color: palette.primary.main,
  },
  pdfSectionHeaderSmall: {
    fontWeight: 600,
    fontSize: "13px",
    color: palette.common.black,
  },
  pdfSectionBody: {
    fontWeight: 400,
    fontSize: "11px",
    color: palette.common.black,
    fontFamily: "Open Sans",
  },
  pdfSectionBodyBold: {
    fontWeight: 700,
    fontSize: "11px",
    color: palette.common.black,
    fontFamily: "Open Sans",
  },
  pdfSectionBodyLarge: {
    fontWeight: 700,
    fontSize: "16px",
    color: palette.common.black,
    fontFamily: "Open Sans",
  },
  pdfSectionBodySmall: {
    fontWeight: 400,
    fontSize: "10px",
    color: palette.common.black,
    fontFamily: "Open Sans",
  },
  pdfSectionBodySmaller: {
    fontWeight: 400,
    fontSize: "9px",
    color: palette.common.black,
    lineHeight: "12px",
    fontFamily: "Open Sans",
  },
  pdfSectionBodySmallest: {
    fontWeight: 400,
    fontSize: "8px",
    color: palette.common.black,
    lineHeight: "10px",
    fontFamily: "Open Sans",
  },
  pdf_h2: {
    fontSize: "30px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "30px",
    fontFamily: "Open Sans",
  },
  pdf_h3: {
    fontSize: "24px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "29px",
    fontFamily: "Open Sans",
  },
  pdf_h4: {
    fontSize: "18px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "22px",
    fontFamily: "Open Sans",
  },
  pdf_h5: {
    fontSize: "16px",
    fontFamily: "Open Sans",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "19px",
  },
  pdf_h6: {
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "17px",
    fontFamily: "Open Sans",
  },
  pdf_body1: {
    fontWeight: 400,
    fontSize: "14px",
    lineHeight: "15px",
    color: palette.common.black,
    fontFamily: "Open Sans",
  },
  pdf_body2: {
    fontWeight: 400,
    fontFamily: "Open Sans",
    fontSize: "12px",
    lineHeight: "15px",
    color: palette.common.black,
  },
  pdf_body3: {
    fontWeight: 400,
    fontSize: "12px",
    lineHeight: "15px",
    color: palette.common.black,
    fontFamily: "Open Sans",
  },
  pdf_body4: {
    fontWeight: 400,
    fontSize: "12px",
    lineHeight: "15px",
    color: palette.common.black,
    fontFamily: "Open Sans",
  },
  pdf_subtitle1: {
    fontWeight: 400,
    fontSize: "12px",
    lineHeight: "15px",
    color: palette.common.black,
    fontFamily: "Open Sans",
  },
});
